#include "forth_io.h"
#include "forth.h"

const CHAR16 num4bit2whex_lut[] = L"0123456789ABCDEF";

void forth_init_io(void)
{
	DFWL(L"EARLY-WEMIT", O_EARLY_WEMIT);
	DESC(L"( WCHAR -- ) \\ EARLY EMIT WCHAR");
	ENDW();
	DFWL(L"EARLY-WKEY", O_EARLY_WKEY);
	DESC(L"( -- WCHAR ) \\ EARLY READ WKEY");
	ENDW();
	DFWL(L"USER-WEMIT", O_USER_WEMIT);
	DESC(L"( -- XT ) \\ GET USER WEMIT XT");
	ENDW();
	DFWL(L"USER-WKEY", O_USER_WKEY);
	DESC(L"( -- XT ) \\ GET USER WKEY XT");
	ENDW();
	DFWH(L"WEMIT");
	DESC(L"( WCHAR -- ) \\ EMIT WCHAR TO OUTPUT");
	COMPILE(L"USER-WEMIT", L"X@", L"EXECUTE", L"EXIT");
	ENDW();
	DFWH(L"WKEY");
	DESC(L"( -- WCHAR ) \\ READ WKEY FROM INPUT");
	COMPILE(L"USER-WKEY", L"X@", L"EXECUTE", L"EXIT");
	ENDW();
	DFWH(L"WTYPE");
	DESC(L"( ADDR CNT -- ) \\ TYPE STRING AT ADDR");
	// : WTYPE DUP IF BEGIN W@ WEMIT 1- SWAP $2 + SWAP DUP 0= UNTIL THEN 2DROP ;
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"OVER", L"W@", L"WEMIT", L"1-", L"SWAP", L"$2", L"+", L"SWAP",
		L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();
	DFWH(L"NUM4BIT>WHEX");
	DESC(L"( N -- WCHAR ) \\ CONVERT NIBBLE TO WHEX");
	COMPILE(L"$F", L"AND", L"2*");
	LIT((uintptr_t)&num4bit2whex_lut[0]);
	COMPILE(L"+", L"W@", L"EXIT");
	ENDW();
	DFWH(L"NHEX.");
	DESC(L"( N C -- ) \\ PRINT N AS HEX WITH WIDTH C");
	// : NHEX. ( NUMBER COUNT -- ) DUP IF BEGIN 2DUP 1- 4 * RSHIFT NUM4BIT>WHEX WEMIT 1- DUP 0= UNTIL THEN 2DROP ;
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"2DUP", L"1-", L"$4", L"*", L"RSHIFT", L"NUM4BIT>WHEX",
		L"WEMIT", L"1-", L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();
	DFWH(L"XHEX.");
	DESC(L"( N -- ) \\ PRINT N AS 16-DIGIT HEX");
	LIT(16);
	COMPILE(L"NHEX.", L"EXIT");
	ENDW();
	DFWL(L"USER-.", O_USER_DOT);
	DESC(L"( -- XT ) \\ GET USER DOT XT");
	ENDW();
	DFWH(L".");
	DESC(L"( N -- ) \\ PRINT TOP NUMBER");
	COMPILE(L"USER-.", L"X@", L"EXECUTE", L"EXIT");
	ENDW();
	DFWH(L"SPACE");
	DESC(L"( -- ) \\ EMIT SPACE CHAR");
	LIT(L' ');
	COMPILE(L"WEMIT", L"EXIT");
	ENDW();
	DFWH(L"CR");
	DESC(L"( -- ) \\ EMIT CARRIAGE RETURN");
	LIT(L'\r');
	LIT(L'\n');
	COMPILE(L"WEMIT", L"WEMIT", L"EXIT");
	ENDW();
	DFWH(L".S");
	DESC(L"( -- ) \\ PRINT STACK CONTENTS");
	// : .S $3C WEMIT DEPTH DUP . $3E WEMIT DUP IF BEGIN SPACE DUP PICK . 1- DUP 0= UNTIL THEN CR DROP ;
	LIT(L'<');
	COMPILE(L"WEMIT", L"DEPTH", L"DUP", L".");
	LIT(L'>');
	COMPILE(L"WEMIT");
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"SPACE", L"DUP", L"PICK", L".", L"1-", L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"CR", L"DROP", L"EXIT");
	ENDW();

	DFWL(L"DELAYUS", O_DELAYUS);
	DESC(L" ( COUNT -- )");
	ENDW();

	DFWH(L"DELAYMS");
	DESC(L" ( COUNT -- )");
	LIT(1000); COMPILE(L"*", L"DELAYUS", L"EXIT");
	ENDW();

	DFWH(L"DELAYS");
	DESC(L" ( COUNT -- )");
	// : TEST-DELAYS DUP IF BEGIN $1 DELAYS DUP . CR 1- DUP 0= UNTIL THEN DROP ;
	LIT(1000 * 1000); COMPILE(L"*", L"DELAYUS", L"EXIT");
	ENDW();

	DFWH(L"CDUMP");
	DESC(L" ( ADDR COUNT -- )");
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"OVER", L"C@", L"$2", L"NHEX.", L"SPACE");
	COMPILE(L"1-", L"SWAP", L"1+", L"SWAP");
	COMPILE(L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();

	DFWH(L"WDUMP");
	DESC(L" ( ADDR COUNT -- )");
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"OVER", L"W@", L"$4", L"NHEX.", L"SPACE");
	COMPILE(L"1-", L"SWAP", L"$2", L"+", L"SWAP");
	COMPILE(L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();

	DFWH(L"LDUMP");
	DESC(L" ( ADDR COUNT -- )");
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"OVER", L"L@", L"$8", L"NHEX.", L"SPACE");
	COMPILE(L"1-", L"SWAP", L"$4", L"+", L"SWAP");
	COMPILE(L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();

	DFWH(L"XDUMP");
	DESC(L" ( ADDR COUNT -- )");
	COMPILE(L"DUP");
	IF();
	BEGIN();
	COMPILE(L"OVER", L"X@"); LIT(16); COMPILE(L"NHEX.", L"SPACE");
	COMPILE(L"1-", L"SWAP", L"$8", L"+", L"SWAP");
	COMPILE(L"DUP", L"0=");
	UNTIL();
	THEN();
	COMPILE(L"2DROP", L"EXIT");
	ENDW();
}
